import { Inter } from "next/font/google";
import "./../globals.css";
import SearchHeader from "@/Component/SearchHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Google Clone",
  description: "Generated by create next app",
};

export default function SearchLayout({ children }) {
  return (
    <div className={inter.className}>
      <SearchHeader />
      {children}
    </div>
  );
}
